apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: suwetha-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql          
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Root@123"
        - name: MYSQL_USER
          value: "college_user"
        - name: MYSQL_PASSWORD
          value: "deereddy@123"
        - name: MYSQL_DATABASE
          value: "mariadb"       
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
          - name: suwetha-mysql
            mountPath: /var/lib/mysql
          - name: initdb-volume
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: suwetha-mysql
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: initdb-volume
          configMap:
            name: sql-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: suwetha-ns
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP