apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc1
  namespace: suwetha-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: duni-sc
